version: 2.1

orbs:
  ssh: circleci/ssh@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
    artifacts:
      - "**/*.html"
      - "**/*.js"
      - "**/*.css"
      - "**/*.map"
      - "**/*.ico"
      - "**/*.svg"
      - "**/*.png"
  deploy:
    docker:
      - image: circleci/python:3.9.5-buster
    steps:
      - ssh/configure:
          name: Configure SSH
          host: 82.165.189.102
          user: minikali
          port: 3333
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - ssh-run:
          name: Deploy Bingo Draw
          command: |
            cd bingo
            git pull
            yarn install
            yarn build
            pm2 restart "Bingo Draw App"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
